# Regresión lineal en Python

## El paquete scikit-learn para regresión lineal y la selección de rasgos

Scikit lo que hace es empezar descartar de manera recursiva cada una de las variables de entrada hasta encontrar el mejor modelo con el número de variables de entrada deseadas que le pasaremos como parámetro. 

In [2]:
from sklearn.feature_selection import RFE  #Recurive Feature Elimination
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("../datasets/ads/Advertising.csv")

In [4]:
feature_cols = ["TV", "Radio", "Newspaper"]

In [5]:
#Divido el data set en 2 para tomar las variables de entrada(X) y las variables de salida (Y)
X = data[feature_cols]
Y = data["Sales"]

In [7]:
estimator = SVR(kernel="linear")   # Uso del modelo LINEAL
selector = RFE(estimator, 2, step=1)   # le paso el número de variables acá! y el número de iteraciones
selector = selector.fit(X,Y)

In [11]:
# con este vemos las variables que nos dejó la evaluación de Scikit Learn
selector.support_  

array([ True,  True, False])

In [14]:
# con este vemos las seleccionadas también porque tiene el número 1, las otras en orden decreciente
selector.ranking_  

array([1, 1, 2])

In [17]:
# a partir de acá también podemos hacer la regresión lineal como antes o usar scikit Learn
from sklearn.linear_model import LinearRegression

In [18]:
X_pred = X[["TV", "Radio"]]

In [20]:
# ACA OCURRE LA MAGIA! 
linear_regresion = LinearRegression()
linear_regresion.fit(X_pred, Y) 

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [21]:
# Se pueden obtener el intercepto:
linear_regresion.intercept_

2.921099912405138

In [22]:
# Se pueden obtener los coeficientes:
linear_regresion.coef_

array([0.04575482, 0.18799423])

In [24]:
# R2 ajustado!
linear_regresion.score(X_pred, Y)

0.8971942610828956